### ISSUE TITLE
How does this actually work on someone's local machine?

### ISSUE THREAD

**Issue by LSleutsky** [ecosse3/nvim#10]
Hey, so this setup looks absolutely incredible!! I would love to start using this asap. I have recently uninstalled Neovim and SpaceVim in an effort to "start fresh" (_I backed up all my older configs of course_), and what I did was just clone down your repo to a random sandbox folder on my Mac, and then just moved the necessary files/folders (_basically everything besides the `screenshots` folder and the `README` file, which obviously are not needed for install_) into `~/.config/nvim`. Is that not right?

I ask because even something as simple as just starting to try and do `:PackerInstall` when inside Neovim yields an error of

```sh
E492: Not an editor command: PackerInstall
```

Am I missing something? Am I doing something wrong, or should I not have moved the folders into the `~/.config/nvim` directory? Any help you could provide would be tremendously appreciated, especially since there is no install guide or quick start guide or anything. In any case, awesome job on this setup!! I hope I get to experience it....

**Comment by ecosse3** [comment]
Hi,
thank you for feedback! 

Since I get this question quite often today I will work on installation shell script. I will let you know when it will be done!

First you have to make sure to install Packer:

> git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

Then you can try to run PackerInstall in headless mode first:

> nvim --headless +'PackerInstall'

Then you can start nvim :)

**Comment by LSleutsky** [comment]
Oh snap, I did not try running Packer in headless mode! But of course I know that Packer had to be installed first (_obviously lol. I'm a noob but not that much of a noob haha_).

An installation script for this incredible config would of course be everyone's dream who has been wanting to use this setup and get the same exact UI that you show in your pics.

In the meantime I will try this headless mode option. Thanks so much for the super fast reply!! 

(_PS, I'm in the middle of like a million different things at once, so if you had a donation button/link that I missed, please either provide it here or DM me, cause I would certainly be willing to donate something for your super hard efforts..._)

**Comment by ecosse3** [comment]
@LSleutsky I just added an installation script in **install_script** branch. Could you check it out?

You have to clone the repo from this branch and put it to _.config/nvim_. Then go to this dir and put commands:

> chmod +x .install/run.sh
> .install/run.sh

Just follow instructions and let me know if that works!
Of course, script will need more changes but I can work on that in days.

**Comment by pvamshi** [comment]
Using it with mac ,  I think one particular module is failing : 


(sorry for the sceenshot , could not copy the text)
<img width="953" alt="image" src="https://user-images.githubusercontent.com/1425006/143682380-2e395a4b-2e9a-400d-9ac5-3d901f0c5a52.png">

**Comment by ecosse3** [comment]
@pvamshi Does it happen during installation via script or after the first run of neovim?
I think it can happen that cmp-tabnine is not installed during installation but we try to use it after the first run.

If you select "Install Plugins" after first run of Ecovim in Dashboard then it works well on the next run?
I'll try to install tabnine via its shell script as well during installation of Ecovim.

**Comment by ecosse3** [comment]
@LSleutsky Were you able to test it?

**Comment by LSleutsky** [comment]
> @LSleutsky Were you able to test it?

@ecosse3 -- My bad, I was unavailable for the last few days and had not had a chance to implement the most current fixes/changes. The commits look promising though, and will definitely get to this in just a couple hours, and make sure to close the issue...

**Comment by LSleutsky** [comment]
So finally able to get to my computer and test this. Same issue with the install script with `PackerInstall` not being an editor command. Will try to tinker with this and hopefully I can get it working. Will report back if I find anything...

**Comment by LSleutsky** [comment]
Yea so, I can't get past the Packer issue. Tried on 3 different machines. Sucks, really wanted to try this config. Maybe down the road I can try it again. Thanks anyway...
