### ISSUE TITLE
When using comment box to comment long line or commented box, the process stuck.

### ISSUE THREAD

**Issue by GuangDai** [ecosse3/nvim#100]
Thank you for this wonderful work, but I find a bug in this project. 
You can see the process keeps running but no result. And usage will keep growing much larger and larger.
![image](https://user-images.githubusercontent.com/59678726/193400728-cc580b51-5af3-4b09-83fd-5f085e6d8adc.png)

![image](https://user-images.githubusercontent.com/59678726/193400729-d6d57ee0-0a65-4319-9098-6042089919b8.png)

**Comment by ecosse3** [comment]
I can reproduce this. Looks like an issue with `https://github.com/LudoPinelli/comment-box.nvim` plugin. Will try to fix it in my own implementation.

**Comment by GuangDai** [comment]
> @GuangDai You can check it again. I think the author of the plugin optimized it and now for me it works correctly even when there is a lot of lines to cover.

Yes, thank you for your kind reply.
