### ISSUE TITLE
HTML auto closing 

### ISSUE THREAD

**Issue by tusheer** [ecosse3/nvim#102]
I can't able to auto-close the HTML tags.

**Comment by Akiletour** [comment]
Maybe it's related : https://github.com/ecosse3/nvim/issues/105

**Comment by PRO-BROS** [comment]
Auto closing is good and it helps [site](https://prhocoding.com/) looks better

**Comment by ecosse3** [comment]
Please re-open the issue if you consider this a bug. I think it's related to #105 and behavior like that is expected.
