### ISSUE TITLE
Wrong date display

### ISSUE THREAD

**Issue by al77ex1** [ecosse3/nvim#110]
```
┌────────────   Today is Ср 26 окт ────────────┐
└───══───══───══───   20:26  ───══───══───══────┘
```
On the dashboard, I see a mismatched right corner of the frame due to the date in the locale language.

Solution:

replace the line in file /lua/plugins/alpha.lua
`-local thingy = io.popen('echo "$(date +%a) $(date +%d) $(date +%b)" | tr -d "\n"')`

to
`+local thingy = io.popen('echo "$(LANG=en_us_88591; date +%a) $(date +%d) $(LANG=en_us_88591; date +%b)" | tr -d "\n"')`

**Comment by ecosse3** [comment]
Thank you for the solution! It will be included in next EcoVim release!
