### ISSUE TITLE
About git blame

### ISSUE THREAD

**Issue by LauGaHo** [ecosse3/nvim#113]
![git](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/9D76kO.png)
which plugin can show the git blame of all lines?

**Comment by kecerud** [comment]
Do you mean those lines that aren't even commited yet? If so, then no plugin will show this to you since it doesn't make any sense right?  (But if you're just asking which plugin does this then check [vim-fugitive](https://github.com/tpope/vim-fugitive) )

**Comment by LauGaHo** [comment]
I found the vim-fugitive, which is helpful to me. Thanks.

**Comment by ecosse3** [comment]
@LauGaHo It's already implemented in Ecovim. Just press `<leader>gb`.

**Comment by LauGaHo** [comment]
> 

OK, Thanks

**Comment by LauGaHo** [comment]
> @LauGaHo It's already implemented in Ecovim. Just press `<leader>gb`.

OK, Thanks
