### ISSUE TITLE
ESLint ENOENT error

### ISSUE THREAD

**Issue by kecerud** [ecosse3/nvim#114]
Hey, this isn't specifically an issue of `Ecovim` per se, rather than part of the config from it but I couldn't find any info related to it online so this is my best bet 🙏 .

After checking out the linting via `eslint` lsp server on save, I am stumbling upon this error (see image) multiple times per day and after that the linter doesn't quite lint the same anymore (meaning that if I open for example VSCode, it lints correctly all the time but after this error, my neovim does crazy stuff).

Do you have any idea what's the case and/or how to fix it? I couldn't find much about this problem online but perhaps some setting up of `root_dir` or something on similar note? 

**This is the config in my `lsp.lua` file:**

<img width="902" alt="Screenshot 2022-11-23 at 22 14 12" src="https://user-images.githubusercontent.com/75565018/203647229-3134a804-4d6c-4b8c-b4cd-fd4b4123aaa9.png">

**This is the error:**

<img width="1949" alt="Screenshot 2022-11-23 at 22 07 13" src="https://user-images.githubusercontent.com/75565018/203646746-ea07c587-efae-4be1-a142-ba5f3f7a303f.png">

PS: If I input `1` to "Open Output" nothing happens and the error message closes itself.

Thanks for looking into this.

**Comment by NiloDrumond** [comment]
Do you have Eslint installed on this project? I'm pretty sure the default Ecovim configs try to format with Eslint on save. If you don't have Eslint on this project then that's for sure the reason.

In that case, you have two options:
- Add eslint to your project (I don't see why you wouldn't use it anyway)
- Change the EslintFixAll command to lsp.buf.format()

**Comment by kecerud** [comment]
@NiloDrumond  Hi Nilo, thanks for reaching out but you probably missed my screenshot/s.

1 - Of course I do have an eslint on my project, it wouldn't make sense not to have it as you mentioned.
2- I already use `lsp.buf.format()` as you can see on the first screenshot:

<img width="738" alt="Screenshot 2022-11-29 at 13 44 11" src="https://user-images.githubusercontent.com/75565018/204532382-39af4a53-ec89-481f-b1f4-4a459af84c76.png">

**Comment by NiloDrumond** [comment]
> @NiloDrumond Hi Nilo, thanks for reaching out but you probably missed my screenshot/s.
> 
> As mentioned in the issue I don't use ecovim as a whole, I just copied part of the code for linting purposes to my own config.
> 
> 1 - Of course I do have an eslint on my project, it wouldn't make sense not to have it as you mentioned. 2- I already use `lsp.buf.format()` as you can see on the first screenshot:
> 
> <img alt="Screenshot 2022-11-29 at 13 44 11" width="738" src="https://user-images.githubusercontent.com/75565018/204532382-39af4a53-ec89-481f-b1f4-4a459af84c76.png">

I see. Sorry for the hasty read. 

From this file in specific, everything looks ok. A few questions that might help us solving your problem are:

1. Does this only happen in this project or in any project?
2. Are the eslint error/warn messages actually appearing on nvim? Or is the Eslint Language Server not working at all?

**Comment by kecerud** [comment]
No worries! Still appreciate the reply.

1 - To be completely honest I'm working on 1 project only at the moment so it happened only in 1 project.
2 - Yeah eslint works completely fine but sometimes when i save a file this error pops out and I have to either restart the LSP multiple times to start linting correctly or quit the whole neovim itself

**Comment by ecosse3** [comment]
@kecerud Is this issue resolved?

**Comment by kecerud** [comment]
@ecosse3 Still happens somewhat often, now also on different projects.

**Comment by ecosse3** [comment]
I wasn't able to reproduce that. Please make a PR in order to fix that.
