### ISSUE TITLE
sumneko_lua (deprecated)

### ISSUE THREAD

**Issue by Badhan-abhishek** [ecosse3/nvim#124]
Hi, 
Thank you for this great repo.
Looks like `sumneko_lua` is deprecated and replaced by `lua_ls`.
I have created a PR #123 for the same but I am new to neovim and lua so don't know if this is exactly what needs to be updated.
It removed warning notifications for me.

**Comment by ecosse3** [comment]
Thank you! It has been merged, I'll release to master soon
