### ISSUE TITLE
how active plugins in lazy ?

### ISSUE THREAD

**Issue by RigottiG** [ecosse3/nvim#125]
I add a plugin in plugins.lua, but it can't load.

![image](https://user-images.githubusercontent.com/13246770/220642984-b444383e-7891-4a91-ae7a-10b14bb26fea.png)

I add this plugin to move lines using <A+k> etc.

```lua
-- /plugins.lua

-- Custom Plugins
-- Move lines
{ "fedepujol/move.nvim", lazy = false }
```

**Comment by ecosse3** [comment]
Not sure why it doesn't start for you. The approach is correct. I've checked and it starts for me:

![image](https://user-images.githubusercontent.com/17691791/220655634-764f1258-ef84-4ed6-9207-6efb14cccbe6.png)

Anyway, you don't need plugins to move lines with Ecovim. It's provided via simple keybinding be default in [nvim/keymappings.lua at master · ecosse3/nvim](https://github.com/ecosse3/nvim/blob/master/lua/config/keymappings.lua#L13-L15)

**Comment by RigottiG** [comment]
@ecosse3 thanks for your answer.

by default, which key do I enter in the "X" mode?

**Comment by ecosse3** [comment]
> by default, which key do I enter in the "X" mode?

`:help mapmode-x`.

> Is there a way to see all keybindings without open its file?

`:Telescope keymaps`
