### ISSUE TITLE
Nvim tree git changes icons and colors dissappear after opening any file

### ISSUE THREAD

**Issue by killerart** [ecosse3/nvim#129]
So git changes show correct icons and colors. But when I open any file (via nvim-tree or telescope) then git icons and colors dissappear.

Neovim 8.3
M1 iMac

**Comment by killerart** [comment]
Started getting the issue after the "lazy" update

**Comment by ecosse3** [comment]
Can you profile more info/screenshots? For me it works as expected:
![image](https://user-images.githubusercontent.com/17691791/224079753-aff3e463-c756-4827-add6-7050632e8c56.png)

**Comment by killerart** [comment]
I downgraded EcoVim to release 2.4.2 and it works without issues

**Comment by killerart** [comment]
Yes, I did change the keybinding to `<leader>e`.
But even when I git clone your master branch without any modifications, the bug still happens

**Comment by killerart** [comment]
Adding `lazy = false` did help indeed

**Comment by killerart** [comment]
Wait, it didn't
I just found out that when I open a usual text file like .gitignore it still works
But if I open any .lua file or .tsx or any other lsp-file, then it breaks (even with `lazy = false`)

**Comment by killerart** [comment]
I don't know what the issue was, but I cleared `~/.local/nvim` and `~/.cache/nvim` and it got fixed.

**Comment by ecosse3** [comment]
I am happy that's resolved! I couldn't reproduce it as well and didn't think that could be a cache problem.
