### ISSUE TITLE
How to cancel the diagnosis of eslint?

### ISSUE THREAD

**Issue by oldqin97** [ecosse3/nvim#130]
How to turn off this diagnosis when I don't want to use eslint and the page does not have an eslintrc file configured?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/48620148/226973629-f280fd20-751e-4d9a-834f-ea0c6384710d.png">

**Comment by ecosse3** [comment]
Please remove the setup function of `eslint` from `lua/lsp/setup.lua`.
