### ISSUE TITLE
Usage of filetypes in LSP

### ISSUE THREAD

**Issue by Akiletour** [ecosse3/nvim#14]
Hello,

Thanks you for your amazing setup :) I love it !

I wanted to know how the LSP configuration files work.

For example on the HTML one, I would like to add filetypes but I don't know how to do it.

Should we do it in M.settings = {}?

Thanks a lot

**Comment by ecosse3** [comment]
Exactly. Everything passed in settings property is passed to server settings. Reference to official lspconfig to see what options HTML has. I will update Readme soon.

**Comment by Akiletour** [comment]
Thanks it's working :)
