### ISSUE TITLE
A problem with Copilot

### ISSUE THREAD

**Issue by al77ex1** [ecosse3/nvim#143]
If I disable the Copilot in the configuration, then the hint popup breaks.

![image](https://github.com/ecosse3/nvim/assets/4921921/e684d41e-7c8c-47c7-8509-75752c3a4b44)

**Comment by al77ex1** [comment]
This is popup with error:

![image](https://github.com/ecosse3/nvim/assets/4921921/e955e47b-0ec0-467c-91e1-4f99d997d2a6)

**Comment by ecosse3** [comment]
@al77ex1 Check `dev` branch. Should be fixed now.
