### ISSUE TITLE
Plugin telescope and neoai not working in v3.5.1

### ISSUE THREAD

**Issue by al77ex1** [ecosse3/nvim#144]
I have this error for telescope plugin in last version:

![image](https://github.com/ecosse3/nvim/assets/4921921/352e09f0-2313-455d-aba4-d7cad7108ed5)

The neoai plugin just doesn't load, so it doesn't work.

![image](https://github.com/ecosse3/nvim/assets/4921921/6013eccc-9bf6-4608-a16b-8523e8343a85)

Plugins worked well in the previous version

**Comment by ecosse3** [comment]
> I have this error for telescope plugin in last version

What neovim version are you using? The errors indicates that you don't have 0.9.0 up.

> The neoai plugin just doesn't load, so it doesn't work.

Make sure to enable it in `EcoVim.lua` config file. It's disabled by default since not everyone has OpenAI API key.

```lua
plugins = {
  ai = {
    chatgpt = {
      enabled = false,  <--- HERE
    },
    codeium = {
      enabled = false,
    },
    copilot = {
      enabled = false,
    },
    tabnine = {
      enabled = false,
    },
  },
{...}
}

**Comment by al77ex1** [comment]
> What neovim version are you using? The errors indicates that you don't have 0.9.0 up.

I just installed the latest version from the wizard, ran the command:
```
git clone https://github.com/ecosse3/nvim.git 
```
Before this sub, I deleted the nvim folders from `~/.config/` and `~/.local/share/`.
After the first launch, I have this screen.
![image](https://github.com/ecosse3/nvim/assets/4921921/64339fc2-a926-486e-9466-3827a3e71dc6)

Although the telescope plugin is installed and working
![image](https://github.com/ecosse3/nvim/assets/4921921/9a79b8bb-003b-4ce6-926f-3b18a76bc363)

> Make sure to enable it in EcoVim.lua config file. It's disabled by default since not everyone has OpenAI API key.

Sorry - I forgot to enable this option.

**Comment by ecosse3** [comment]
You can clearly see that you have Neovim v0.8.0 which is not supported by telescope.nvim anymore. That's why you have this error. I'll bump the minimal required neovim version for Ecovim to 0.9.0. About `nil` please create a new issue or check on v0.9.0 neovim first.

**Comment by al77ex1** [comment]
Thanks for support! The problem was related to nvim version.
