### ISSUE TITLE
telescope search not work

### ISSUE THREAD

**Issue by AlucPro** [ecosse3/nvim#146]
error occur when s-p
<img width="1750" alt="image" src="https://github.com/ecosse3/nvim/assets/52643141/ac3d9f7f-e52f-4a8d-b34a-2f90b78c09c7">

**Comment by ecosse3** [comment]
I am not able to reproduce it. Do you have updated packages? What Neovim version do you use? Looks like your local issue.

**Comment by ecosse3** [comment]
Please make sure to use Neovim 0.9+. I consider this issue as stale.

**Comment by killerart** [comment]
I have the save issue on neovim 0.10.2
