### ISSUE TITLE
Tsserver doesn't work properly

### ISSUE THREAD

**Issue by szoradigeza** [ecosse3/nvim#149]
Hi,
I'm using the latest version of the config. 
It looks like the tsserver doesn't work properly.
I tried to debug it, but didn't find the solution.

![Screenshot 2023-06-14 at 17 12 43](https://github.com/ecosse3/nvim/assets/35313105/d678f42e-2832-4c90-8438-c05ca95e3b5e)

Do you have any idea what the problem can be?

**Comment by ecosse3** [comment]
Further information is required.

Logs from `:LspInfo`, `:MasonLog` etc. It can be your project/local issue.

**Comment by szoradigeza** [comment]
We can close it. A node_modules reinstalling resolved the issue.
