### ISSUE TITLE
Codeium Auth

### ISSUE THREAD

**Issue by al77ex1** [ecosse3/nvim#151]
Recently the new OS Debian 12 came out and I reinstalled my system (Debian 11 -> Debian 12).
I have a problem with authentication in Codeium.
Previously, I just updated Ecovim and this problem did not arise because authorization was preserved in the system.
![image](https://github.com/ecosse3/nvim/assets/4921921/a57b819d-8e8f-437a-895c-8832b5151d24)
This error occurs when selecting any menu item after the command "Codeium Auth".

nvim: v0.9.1
EcoVim: v3.5.2
node: v18.12.1
npm: v8.19.2
yarn: v1.22.19

**Comment by ecosse3** [comment]
Hi, currently I have the same issue. It's an issue with Codeium for nvim. Nothing to do with Ecovim. We need to wait.
