### ISSUE TITLE
why does it hide the imports?

### ISSUE THREAD

**Issue by peteblank** [ecosse3/nvim#152]
So i like this don't get me wrong but I can't use it if its going to start hiding imports and/or deleting them.

**Comment by ecosse3** [comment]
This is a `nvim-ufo` plugin. You can remove it.

First remove it from `plugins.lua`:
https://github.com/ecosse3/nvim/blob/69747da5530b4947e8d9fb157997201060c818c9/lua/config/plugins.lua#L418-L426

Then in `lsp/setup.lua` (in require too):
https://github.com/ecosse3/nvim/blob/69747da5530b4947e8d9fb157997201060c818c9/lua/lsp/setup.lua#L137-L140

And jest leave `vim.lsp.buf.hover()` in `keymappings.lua`:
https://github.com/ecosse3/nvim/blob/69747da5530b4947e8d9fb157997201060c818c9/lua/config/keymappings.lua#L133-L138
