### ISSUE TITLE
after updating i get alot of errors, how can i debug it?

### ISSUE THREAD

**Issue by al3rez** [ecosse3/nvim#155]
<img width="516" alt="Screenshot 2566-07-11 at 04 08 02" src="https://github.com/ecosse3/nvim/assets/15009059/94151816-4e12-455e-b0b1-46e441d0f018">

**Comment by ecosse3** [comment]
I had this error once, and I described everything in the issue of `typescript-tools` here: https://github.com/pmizio/typescript-tools.nvim/issues/70

Unfortunately, I am not able to reproduce this issue anymore. Seems it was related to ESLint. I will try to replicate this issue and see if somehow I can fix it. Could you please provide more details? Reproduction example? What nvim version do you use? TypeScript version? ESLint version?

**Comment by al3rez** [comment]
it seems it was related to node version after swithcing to v18+ it's fixed.

**Comment by al3rez** [comment]
it seems it was related to node version after swithcing to v18+ it's fixed.

**Comment by al3rez** [comment]
it seems it was related to node version after swithcing to v18+ it's fixed.
