### ISSUE TITLE
Alternative for null-ls? 

### ISSUE THREAD

**Issue by alfredosdpiii** [ecosse3/nvim#156]
I think efm might be a good alternative

**Comment by ecosse3** [comment]
For now this is on hold, since with Frontend development we mostly don't need independent formatter. You can configure `prettier` per project what I recommend. I consider using [mhartington/formatter.nvim](https://github.com/mhartington/formatter.nvim) in future, but now adding formatter plugin to EcoVim **on your own** is recommended.

**Comment by alfredosdpiii** [comment]
For now I use [Neoformat](https://github.com/sbdchd/neoformat) because I only need prettier anyways 

I'll also try to use [formatter.nvim](https://github.com/mhartington/formatter.nvim) in the future

**Comment by ecosse3** [comment]
Just to let you know all. I'm testing Ecovim with [stevearc/conform.nvim: Lightweight yet powerful formatter plugin for Neovim](https://github.com/stevearc/conform.nvim) and [mfussenegger/nvim-lint: An asynchronous linter plugin for Neovim complementary to the built-in Language Server Protocol support.](https://github.com/mfussenegger/nvim-lint) right now and it works great. I may release it soon as alternative to `null-ls`.

**Comment by ayushkmr2009** [comment]
> For now this is on hold, since with Frontend development we mostly don't need independent formatter. You can configure `prettier` per project what I recommend. I consider using [mhartington/formatter.nvim](https://github.com/mhartington/formatter.nvim) in future, but now adding formatter plugin to EcoVim **on your own** is recommended.

which plugin is being used right now, because i am searching for the config file (idk where it is) so that i can configure **black** formatter for python and maybe _pylint,isort_ too if possible

**Comment by ecosse3** [comment]
It's done in `v4.0.0`.
