### ISSUE TITLE
 MasonLog: Installation failed for Package(name=html-lsp) error=spawn: npm failed with exit code 1 and signal 0.

### ISSUE THREAD

**Issue by zerrol** [ecosse3/nvim#157]
I install the config  of nvim succussful, but Mason install package failed.

I already installed node and npm.

```
node version: v20.4.0 (installed by homebrew)
npm version: 9.7.2
nvim version: 0.9.1
```

Please help ~~ 

<img width="1340" alt="image" src="https://github.com/ecosse3/nvim/assets/9137993/b4bcd1fe-90f5-4582-ac27-0367df7fbbd5">

**Comment by zerrol** [comment]
Error stack
<img width="1187" alt="image" src="https://github.com/ecosse3/nvim/assets/9137993/39235ae9-d076-41ff-85a0-8c228dcad20e">

**Comment by ecosse3** [comment]
> EACCES: permission denied

This is somehow related to your installation of `npm`/`node`.  Install it without `sudo`. Looks like it's **not related to Ecovim**.

**Comment by zerrol** [comment]
The problem was resolved. Thanks
>  https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
