### ISSUE TITLE
Issue right after install

### ISSUE THREAD

**Issue by Antonio-Rocchia** [ecosse3/nvim#158]
I'm running Fedora 38 and I got this error after opening my first javascript file:
...pt-tools.nvim/lua/typescript-tools/tsserver_provider.lua:133: Cannot find tsserver executable i
n local project nor global npm installation.
stack traceback

I've tried removing neovim state, cache and config folder and reinstalling the distribution.
I've also tried installing tsserver via Mason

**Comment by pmizio** [comment]
Hello, I'm author of [typescript-tools.nvim](https://github.com/pmizio/typescript-tools.nvim). You get error from it and error says exactly what is going on - typescript isn't installed in paths known by npm:
- local installation means node_modules inside your current project
- global installation means typescript installed on system level eg. `npm i -g typescript` or using your distros package manager

Currently plugin don't support Mason installed paths but if you want to use it you can do this manually using following https://github.com/pmizio/typescript-tools.nvim/issues/106#issuecomment-1637124589 snippet.

I hope it helps and sorry @ecosse3 for interfering ;}

**Comment by ecosse3** [comment]
@Antonio-Rocchia Explanation provided by @pmizio should help you solve that issue.

@pmizio Thanks, I was busy last time and didn't look into Ecovim issues 😄 I'll look into solution of using tsserver installation path from `Mason` and maybe add it to `Ecovim`!
