### ISSUE TITLE
Copilot - Codeium

### ISSUE THREAD

**Issue by gmmoose20** [ecosse3/nvim#165]
I don't know why when I set the copilot = false in my Ecovim.lua and only set codeium = true. I don't get any autocompletion. Do I really need the Copilot to be enabled to be able to use Codeium and get autocompletion? 🤔

**Comment by ecosse3** [comment]
Thanks for the issue! I didn't use `codeium` daily recently, so I didn't notice it. It should work after https://github.com/ecosse3/nvim/commit/07629b5b730012ef180149158d8bc07cf6881104.

You need to reload nvim & "Update Plugins" after change in EcoVim.lua.
Also, make sure to run `:Codeium Auth` command to get the token.

I noticed that sometimes you need to click <C-Space> again to get Codeium autocompletion. It may be a bug in `cmp` and I cannot fix it at this moment. Please don't hesitate to open PRs.

**Comment by al77ex1** [comment]
I have same as problem. I have token in config file for codeium plagin in cache. 
This issue appear when I set option 'copilot = false'  
if I i restore option value to 'true' - autocompletion is work with codeium plugin.

**Comment by Pkcarreno** [comment]
This is not just a Codeium issue, I was playing with this for a bit. For some reason, when disabling Copilot, the entire autocompletion breaks. To test it just disable Copilot (without enabling other AI) and autocompletion stop working.

I still trying to figure out why this happened, https://github.com/ecosse3/nvim/commit/07629b5b730012ef180149158d8bc07cf6881104 seems to not make any difference.

I update here if I find something

**Comment by Pkcarreno** [comment]
> This is not just a Codeium issue, I was playing with this for a bit. For some reason, when disabling Copilot, the entire autocompletion breaks. To test it just disable Copilot (without enabling other AI) and autocompletion stop working.
> 
> I still trying to figure out why this happened, [07629b5](https://github.com/ecosse3/nvim/commit/07629b5b730012ef180149158d8bc07cf6881104) seems to not make any difference.
> 
> I update here if I find something

Dev branch working properly*
I hadn't tested the entire branch until now
