### ISSUE TITLE
`indent-blanklink` has deprecated settings

### ISSUE THREAD

**Issue by Pkcarreno** [ecosse3/nvim#166]
It gives me this error message:

![Screenshot from 2023-10-05 18-22-54](https://github.com/ecosse3/nvim/assets/34664891/2ff4d603-5869-4296-8ac9-7d1bb0414d4c)

These values are deprecated in the `indent-blankline` config (`lua/plugins/indent.lua`)

```lua
  show_current_context = true,
  show_current_context_start = false,
  show_end_of_line = false,
```

Removing them works as a workaround but I did not get any alternative settings.
But I found this: https://github.com/lukas-reineke/indent-blankline.nvim/issues/666

**Comment by al77ex1** [comment]
I just removed these options

**Comment by ecosse3** [comment]
@Pkcarreno This is already fixed on `dev` branch and `indent-blankline` plugin configuration is updated to the newest version. I'll make a new EcoVim release soon and it will be included there.
