### ISSUE TITLE
ts_context_commentstring/internal.lua:135 error

### ISSUE THREAD

**Issue by jayaadeep11** [ecosse3/nvim#171]
stack traceback:
	...-commentstring/lua/ts_context_commentstring/internal.lua:135: in function 'attach'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_exec_autocmds'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:157: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:156>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:156: in function 'trigger'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:87: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:72>
	...
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:30: in function </usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:289: in function 'open_in_new_window'
	...y/nvim-tree.lua/lua/nvim-tree/actions/node/open-file.lua:338: in function 'fn'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:180: in function 'edit'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:192: in function 'fn'
	...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:50: in function <...ocal/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree/api.lua:47>

**Comment by ecosse3** [comment]
@JayaDeep11 Should be fixed now in v3.9.0. Please let me know.
