### ISSUE TITLE
Neovim exits immediately on startup after fresh install

### ISSUE THREAD

**Issue by alarwasyi98** [ecosse3/nvim#179]
### Description
I've recently set up Ecovim on my Ubuntu as per the instructions in the repository. The installation process completed without any errors, and all plugins were loaded successfully. However, when I start Neovim, it does not load the dashboard or open my workspace. Instead, Neovim suddenly exits, and my terminal reverts to the bash prompt. Because of this, I'm unable to run any commands, including :checkhealth.

### Steps to Reproduce:
1. Follow the installation steps for Ecovim on the repository.
2. Start Neovim by typing nvim in the terminal.
3. Observe the behavior.

### Expected Behavior:

Neovim should display the dashboard and load the workspace as configured.

### Actual Behavior:

Neovim suddenly exits and returns to the bash prompt. I am unable to run any Neovim commands, including :checkhealth.

### System Information:

OS: Ubuntu 22.04.4 LTS (WSL)
Neovim version: v0.10.0
Ecovim version: v3.9.0

### Additional Information:

- No errors appeared during the plugin installation.
- Installation in WSL Ubuntu
![issue1](https://github.com/ecosse3/nvim/assets/88342618/e199b856-531b-4540-a633-1dc1d721d18c)
![Screenshot_141](https://github.com/ecosse3/nvim/assets/88342618/400b1b98-7de7-4939-9344-7db59c79e7ca)

I would appreciate any help in diagnosing and resolving this issue.

Thank you!

**Comment by H4ckint0sh** [comment]
@alarwasyi98 Install using the installer `sh ./install/run.sh `.
