### ISSUE TITLE
How to disable openrgb

### ISSUE THREAD

**Issue by kpritam** [ecosse3/nvim#2]
I have rgb keyboard but dont want to install opnenrgb server.

Is there any way to disable it?
If I remove openrgb plugin or change anything else status line does not seem to be working.

It shows when nvim is opening but on focus gain it goes away.

**Comment by ecosse3** [comment]
Hi @kpritam.

Just remove openrgb plugin from **/vim-plug/plugins.vim** and corresponding config file for it from init.vim.

Then remove line 88 in **/general/statusline.vim**:

`let l:statusline .= OpenRGBStatuslineFunc()`

It should work. Let me know if it works.

**Comment by kpritam** [comment]
Thanks, I did try that, status line gets displayed for fraction of second when nvim is opening but as soon as focus gets shifted to opened file, statusline vanishes. Is that a feature or I am missing something?

**Comment by ecosse3** [comment]
No, it shouldn't be like that. Do you have any errors showing when you open neovim and statusline vanishes? Maybe you're missing some necessary plugin and that's why it breaks. In my statusline I'm using references to gitsigns.nvim and that's all. Did you clone lua branch? In master which is I was using also fugitive.vim but I'll update master to lua branch soon.

**Comment by ecosse3** [comment]
That's weird. Could you try to run vim from another terminal like kitty? I'm using kitty and don't have any problems. If we can't solve this problem you can try to use some different status line like galaxyline etc.

**Comment by kpritam** [comment]
Tried with kitty, same result. Maybe I ll try galaxyline.

**Comment by kpritam** [comment]
Galaxyline and airline etc as well did not work which forced me to delete ~/.nvim and ~/.local/share/nvim dir and reinstall everything. After doing this, I can confirm that this is working as expected, thanks!
