### ISSUE TITLE
Can't open lazygit

### ISSUE THREAD

**Issue by devpaps** [ecosse3/nvim#27]
First i just want to say thank you for this project that you've made opensource! Because of you i started to use Neovim im my day to day workflow! 👍🏻 

So my issue is that when a want to open LazyGit it just opens for like 0.5 seconds then immediately closes. I'm in a project that uses git. When i want to open LazyGit i press <leader>gg.

**Comment by ecosse3** [comment]
I think it can be related to lazygit itself. Does it work when you open lazygit from terminal? What lazygit version and OS you have?

**Comment by devpaps** [comment]
Oh, my bad.
Didn't know that i had to install LazyGit separately. I've now got it working by installing it via Homebrew wtih this command, `brew install jesseduffield/lazygit/lazygit`. 😄  Well i've learned something new today.
