### ISSUE TITLE
Install Script not working

### ISSUE THREAD

**Issue by Ruhtra47** [ecosse3/nvim#29]
I wanted to install it, but the installation script freezes when installing plugins, and then it is half installed, so I can't use it correctly and I have to remove all the configuration manually.
![image](https://user-images.githubusercontent.com/65797068/153883846-26e0854c-0e0f-41a3-88ba-311838377f85.png)
![image](https://user-images.githubusercontent.com/65797068/153883996-3fef567f-df20-4906-9e60-330fd1798191.png)
Am I doing something wrong?

**Comment by ecosse3** [comment]
@Ruhtra47 Thank you for this issue! I was able to replicate it. Looks like treesitter update somehow breaks when working in headless mode. I fixed that now. Could you please run the installer from dev branch via this command:

`bash <(curl -s https://raw.githubusercontent.com/ecosse3/nvim/dev/.install/run.sh)`

Let me know if it works now 😄  Then I will merge it to master.

**Comment by Akiletour** [comment]
@ecosse3 from your dev branch, everything seems to be going well. If this can help

![CleanShot 2022-02-15 at 00 32 29](https://user-images.githubusercontent.com/1524422/153964746-5fb440b0-6fdd-4a2d-b671-a0f47bec0437.jpg)

**Comment by ecosse3** [comment]
Great! Merged to master.

**Comment by ecosse3** [comment]
@Ruhtra47 Please let me know if that works for you too.

**Comment by Ruhtra47** [comment]
It installed just fine and it's working. And I'm WOW!!! Awesome project!!
