### ISSUE TITLE
Using impatient/mpack on a Mac M1

### ISSUE THREAD

**Issue by Akiletour** [ecosse3/nvim#30]
Hello @ecosse3 

I'm using ecovim on Mac and I'm having a problem with `impatient` and `mpack`.

It is not possible to install `mpack` on Mac. 

Is this extension mandatory? Is there an alternative ?

![CleanShot 2022-02-15 at 00 48 37](https://user-images.githubusercontent.com/1524422/153966173-285654bf-abb5-43e7-8774-5c50e8328c92.jpg)

If you have an idea, I'm interested

**Comment by ecosse3** [comment]
I see that `vim.mpack` is now builtin to neovim so there is no need to require it. I will remove it from rocks of impatient. Maybe you're missing some dependency to build it from source but that's not needed anyway 😊

You can remove `rocks = 'mpack' ` from impatient in nvim and it should work.
