### ISSUE TITLE
Opening the file explorer 

### ISSUE THREAD

**Issue by devpaps** [ecosse3/nvim#33]
I've re-installed Ecovim now, but whenever i ~~want to open a file~~ toogle the file explorer, the nvim-tree do a vertical split of the file that it's currently on in the file explorer. See the clip below.

Anyone else is having this issue?

https://user-images.githubusercontent.com/12218443/155346923-9190c2fe-8899-43ff-a32a-5c76c714ddcf.mp4

**Comment by Akiletour** [comment]
Hello,

Which key did you use to open the file? Just "Enter"?

**Comment by devpaps** [comment]
Hi!
Yes, i am.

This has never happened before. Have they done any changes in nvim-tree.lua?

**Comment by devpaps** [comment]
I want to clarify that it splits the file when i don't select i file i want to open. In other words, when i toogle the file explorer, <C-e>.

**Comment by ecosse3** [comment]
@devpaps I can reproduce this issue. It's probably related to some of the nvim-tree update. Let me fix that and I will let you know.

**Comment by ecosse3** [comment]
@devpaps Fixed on `dev` branch. Probably will make a release to master soon.

Fixed in commit: https://github.com/ecosse3/nvim/commit/6485cf204f038a093c0c7191b281a8752d65e388
