### ISSUE TITLE
could you please add support for angularjs

### ISSUE THREAD

**Issue by rajcspsg** [ecosse3/nvim#36]
Hi,

could you please add support for angular lsp https://github.com/angular/vscode-ng-language-service

**Comment by ecosse3** [comment]
Hi. I do not plan to add it at least for now but soon I want to investigate more into adding more LSP supports to this project. Anyway, pull requests are welcome 😄

**Comment by FortinFred** [comment]
You should remove Angular from this statement then:

Quote:
Configured for TypeScript Development (React.js, Next.js, Vue.js, Angular, Node.js etc.)
