### ISSUE TITLE
error on autocompletion because of cmp documentation deprecation

### ISSUE THREAD

**Issue by XenoWad01** [ecosse3/nvim#39]
`documentation = {...}` was deprecated in favour of `window = { documentation = ...}`. Also I don think you need to state the window borders anymore in an object you can just do `window = { documentation = cmp.config.window.bordered() }` inside the cmp.lua config file. Sorry if I explained it badly.

**Comment by ecosse3** [comment]
Thanks. Fixed in Ecovim Release v1.4.0:
https://github.com/ecosse3/nvim/releases/tag/v1.4.0
