### ISSUE TITLE
How to install in a mac environment?

### ISSUE THREAD

**Issue by H4ckint0sh** [ecosse3/nvim#4]
It gives me far too many errors, and cant run PlugInstall
<img width="922" alt="Skärmavbild 2021-09-25 kl  17 39 28" src="https://user-images.githubusercontent.com/44159647/134777216-8e6770a6-382b-4209-a6f1-21fc428f3313.png">
.

**Comment by ecosse3** [comment]
That's because I am using OpenRGB plugin for my keyboard. I will remove it from repo today. For now please remove line 83:

`use {'antoinemadec/openrgb.nvim', run = ':UpdateRemotePlugins'}` from _lua/plugins/init.lua_.

Then also remove line 7:

`source $HOME/.config/nvim/vim-plug/openrgb.vim    " OpenRGB` from _init.vim_.

Let me know if that works.

**Comment by H4ckint0sh** [comment]
Now i get this among some other errors.
<img width="1182" alt="Skärmavbild 2021-09-27 kl  20 25 36" src="https://user-images.githubusercontent.com/44159647/134964848-7ee3fac2-bea2-4571-84a1-35232f2c3fe7.png">

**Comment by H4ckint0sh** [comment]
I still am not able to run PackerCompile allthupgh it is working if i switch to my own config.

**Comment by ecosse3** [comment]
You can first comment out first line in _init.vim_ which is:
`lua require('impatient')`

Then you can comment on everything and leave require of plugins and settings in _init.lua_ and run PackerInstall. After everything will be installed you can uncomment each by each to check where the problem occurs.

**Comment by H4ckint0sh** [comment]
Thankyou, how can i solve this? I have installed html server by :lspInstall html but it still does not work.
<img width="1602" alt="Skärmavbild 2021-09-20 kl  22 04 18" src="https://user-images.githubusercontent.com/44159647/134996841-74bef9d4-cf74-42e6-8cc2-e7c600f9f77a.png">

**Comment by ecosse3** [comment]
I close it as it works solves problem from this issue.

To make HTML Language Server work you have to install globally via npm/yarn the `vscode-html-language-server` as vim is giving you a hint. Check out `:LspInfo` to see what servers are enabled in the current file.

`npm install -g vscode-html-language-server`

I am actually using now `vscode-langservers-extracted`.
