### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by EPolovniy** [ecosse3/nvim#44]
![image](https://user-images.githubusercontent.com/48632943/167312884-0ec07c83-58fb-4b9a-8c30-672d0f4ef33f.png)

**Comment by ecosse3** [comment]
Could you please run "Install Plugins" from dashboard or do `:PackerInstall` and then `:PackerSync`. I added new utility plugins for typescript with LSP and looks like you don't have it installed. I'll make commit to prevent displaying (and loading tsserver LSP) if that plugin is not enabled.

**Comment by EPolovniy** [comment]
Thanks! Error disappeared ) But I notice that format not working for JS files.

**Comment by ecosse3** [comment]
Good! Please open an issue with more details. It can be also related to configuration of project.
