### ISSUE TITLE
Enable to format a tsx document

### ISSUE THREAD

**Issue by Akiletour** [ecosse3/nvim#45]
Hi @ecosse3 :)

When I try to run the "<leader> cf" command, an error appears: 
![CleanShot 2022-05-09 at 21 58 19](https://user-images.githubusercontent.com/1524422/167487814-14eefc5c-6b5b-41d5-85fe-b2abc6912cd7.jpg)

Any idea ?

**Comment by ecosse3** [comment]
That's because your are not using the newest neovim nightly. They have changed the API.

**Comment by Akiletour** [comment]
Thanks :)
