### ISSUE TITLE
'TabNine' is not executable

### ISSUE THREAD

**Issue by Pilchh** [ecosse3/nvim#49]
After fiddling around with the config and reinstalling it multiple times, I got everything working apart from whenever I enter insert mode or use fzf, I get the following error. Any idea what is going on?

```
Error executing vim.schedule lua callback: Vim:E475: Invalid value for argument cmd: '/home/pilchh/.local/share/nvim/sit
e/pack/packer/opt/cmp-tabnine/binaries/4.4.8/x86_64-unknown-linux-musl/TabNine' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...e/pack/packer/opt/cmp-tabnine/lua/cmp_tabnine/source.lua:234: in function '_on_exit'
        ...e/pack/packer/opt/cmp-tabnine/lua/cmp_tabnine/source.lua:135: in function 'new'
        ...ite/pack/packer/opt/cmp-tabnine/lua/cmp_tabnine/init.lua:8: in function <...ite/pack/packer/opt/cmp-tabnine/l
ua/cmp_tabnine/init.lua:7>
```

Side note: Is it possible to make nvim tree have a transparent background?

**Comment by ecosse3** [comment]
I'm wondering you need to open an issue in https://github.com/tzachar/cmp-tabnine about this error. Not sure if tabnine can work with WSL. In case you don't need it you can remove `tzachar/cmp-tabnine` from `plugins.lua` and config from `lua/plugins/tree.lua`.

> Side note: Is it possible to make nvim tree have a transparent background?

You can find Nvim Tree highlights groups by `:Telescope highlights` and change them by:

```lua
vim.highlight.create('NvimTreeNormal', { guibg = "None", guifg = "None" }, false);
```

`None` for transparent or `#HEX` for color.

**Comment by Pilchh** [comment]
I've made an issue with https://github.com/tzachar/cmp-tabnine so we will see how that goes. Thanks for the info on making the tree transparent. Looks like I've got everything sorted minus this tabnine issue.

**Comment by ecosse3** [comment]
@Pilchh Not sure if it will work, but just a tip from me: `cd` into `~/.local/share/nvim/site/pack/packer/opt/cmp-tabnine/binaries/4.4.8/x86_64-unknown-linux-musl` directory and run `chmod +x TabNine`. Then rerun nvim. Maybe it will solve issue with tabnine.

**Comment by Pilchh** [comment]
@ecosse3 I gave that a go but it didn't change anything. I'll try and work with the `cmp-tabnine' team to try and figure it out.
