### ISSUE TITLE
How to get rid off all of Prettier messeages?

### ISSUE THREAD

**Issue by H4ckint0sh** [ecosse3/nvim#5]

**Comment by ecosse3** [comment]
Please provide more information about your issue.

**Comment by H4ckint0sh** [comment]
![Skärmavbild 2021-09-30 kl  11 32 17](https://user-images.githubusercontent.com/44159647/135427234-cf8a2bda-64b3-428c-9c12-c119953ebb25.png)

**Comment by ecosse3** [comment]
This is related to your personal .prettierrc.json config or eslint config. Update your global/project prettier version, change your configuration of project. It's not related to my nvim configuration.
