### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by sean-brydon** [ecosse3/nvim#51]
<img width="1130" alt="CleanShot 2022-06-01 at 10 35 59@2x" src="https://user-images.githubusercontent.com/55134778/171374683-7a55710d-6f84-4b83-be64-6a8cbb73f086.png">
Hello - I am trying to install a fresh install of this setup and I am getting this error - any idea?

**Comment by ecosse3** [comment]
Hi, thanks for reporting. It was due to a broken Dashboard plugin. I exchanged it with Alpha and changed the installation script. It should work now. Please let me know.

**Comment by sean-brydon** [comment]
Closing - thanks for the prompt fix
