### ISSUE TITLE
E492: Not an editor command: PackerSync

### ISSUE THREAD

**Issue by Chaqua** [ecosse3/nvim#54]
So I tried multiple fixes, and none of them worked. It is thrown when I use the command  `bash <(curl -s https://raw.githubusercontent.com/ecosse3/nvim/master/.install/run.sh)`. I know its probably not a bugg or smth, but after searching for the right solution for hrs, I dont know anymore haha

Also, I am very sorry abt my bad english, if u cant understand smth, just tell me :)

**Comment by ecosse3** [comment]
What OS are you using? Do you have packer already installed?

I was testing my installation script on macOS, Ubuntu, Arch and even Alpine Linux in Docker and the installation works well. You can even try my config with docker:

```sh
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git bash fuse nodejs dpkg wget npm fzf ncurses neovim ripgrep alpine-sdk --update
  wget https://raw.githubusercontent.com/ecosse3/nvim/master/.install/run.sh -O run.sh
  chmod +x run.sh && bash run.sh
  nvim
  '
```

You can also check if you have already packer installed, maybe it's worth removing it completely.
The dir should be `~/.local/share/nvim/site/pack/packer/`.

**Comment by Chaqua** [comment]
I am on windows, and using the ubunut terminal. I have packer installed, and yeah it is under `~/.local/share/nvim/site/pack/packer/` .  Is there anything I maybe have to setup or smth? I can run packer -v without any trouble

**Comment by ecosse3** [comment]
@Chaqua Unfortunately I don't have Windows so I'm unable to check this right now. I do not plan to support Windows/WSL by now. Any PRs to support/fix that are welcome.

**Comment by d0t15t** [comment]
Make sure you're on the newest version of neovim - that was my problem!

**Comment by ecosse3** [comment]
@Chaqua Could you check if that works? Unfortunately, I still don't have access to the Windows machine and WSL.

**Comment by luccasFelippeOliveira** [comment]
Had the same problem, by installing the latest neovim version from the github repository solved the problem. Could it be the neovim version? In the ubuntu wsl package neovim is on version v.0.4.3 and it's from november 2019, might be too old.

**Comment by ecosse3** [comment]
@luccasFelippeOliveira For sure Ecovim will not work with neovim 0.4 or even 0.6. It uses API from 0.7 and 0.8 nightly if available. @Chaqua Does it work to you with latest stable neovim version on WSL?

**Comment by amanzrx4** [comment]
I was on 0.4, upgrading to 0.7 worked for me, cheers!
