### ISSUE TITLE
nvim 0.8 (nightly) install issue - winbar

### ISSUE THREAD

**Issue by AlanWarren** [ecosse3/nvim#55]
Hello,

I've tried both master + dev branches, but i'm getting the same error when running the installer script. 
```sh
Error detected while processing BufWinEnter Autocommands for "*":
Error executing lua callback: /Users/alan/.config/nvim/lua/autocmds.lua:40: attempt to index a boolean value
stack traceback:
        /Users/alan/.config/nvim/lua/autocmds.lua:40: in function </Users/alan/.config/nvim/lua/autocmds.lua:18>
Press ENTER or type command to continue
```

Post install, nvim opens and packer fetches everything ok it seems.  Following plugin installation, nvim opens with the following error. 

```sh
Error detected while processing BufWinEnter Autocommands for "*":
Error executing lua callback: /Users/alan/.config/nvim/lua/autocmds.lua:40: attempt to index a boolean value
stack traceback:
        /Users/alan/.config/nvim/lua/autocmds.lua:40: in function </Users/alan/.config/nvim/lua/autocmds.lua:18>
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:110: Vim(append):Error executing lua call
back: /Users/alan/.config/nvim/lua/autocmds.lua:40: attempt to index a boolean value
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/l
ua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

Sorry I don't feel capable of debugging this, as i'm not sure if the lua api has regressed somewhere, etc.  This is my first steps into any of the new lua features in nvim.

Thanks!

**Comment by ecosse3** [comment]
What neovim version do you have? Could you check if you have latest nightly? I've checked on 3 different OS and the installer works fine. Maybe you have 0.8 version which doesn't have winbar support yet, I'm not sure. Try commenting everything from line 16 to bottom in `lua/autocmds.lua`.

**Comment by AlanWarren** [comment]
I was using NVIM v0.8.0-dev+359-g9745941ef

Just grabbed the latest nightly -  NVIM v0.8.0-dev+374-ge13dcdf16
Same error as above.  :(

**Comment by AlanWarren** [comment]
I've tried commenting everything from line 16 to the bottom on `lua/autocmds.lua`.  The error does go away, but each time I open neovim it lists the following language servers are being installed. 

```sh
(automatic installation) Installing LSP server: tsserver
(automatic installation) Installing LSP server: tailwindcss
(automatic installation) Installing LSP server: eslint
(automatic installation) Installing LSP server: jsonls
(automatic installation) Installing LSP server: sumneko_lua
(automatic installation) Installing LSP server: vuels
(automatic installation) Installing LSP server: bashls
(automatic installation) Installing LSP server: cssls
(automatic installation) Installing LSP server: graphql
(automatic installation) Installing LSP server: html
(automatic installation) Installing LSP server: volar
Press ENTER or type command to continue
```

After pressing `ENTER` nvim opens with autocmds.lua loaded as a buffer.   (not sure why it's doing that) 
If I execute `:messages` I can see the following. 

```sh
Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
Press ENTER or type command to continue
```
Also, just curious. Why does your installer reset my bat theme?   I can resolve this with `bat cache --build` but just seems odd.  

Appreciate it

**Comment by ecosse3** [comment]
> but each time I open neovim it lists the following language servers are being installed.

Servers should be installed just once and then message should dissapear, I know it's annoying and there is opened issue for that -> https://github.com/williamboman/nvim-lsp-installer/issues/702
You can try to remove `sumneko_lua` from `lua/lsp/setup.lua` as it's in the list to auto install LSPs. Then you can manually install it with :LspInstall. Maybe then it won't fail. To me it installs each time correctly.

> After pressing ENTER nvim opens with autocmds.lua loaded as a buffer.

Sounds like session-manager auto opens last saved session (if possible). I removed this as default with Ecovim 1.9.0, so if it's not that I don't know answer why it's doing it. You can check in `lua/plugins/session-manager.lua`

> Why does your installer reset my bat theme?

I don't know answer to this question. I don't have anything related to `bat` in my config so I guess it's not Ecovim fault.

**Comment by ecosse3** [comment]
@AlanWarren I was able to reproduce this issue on Linux. On MacOS it was working fine. I'll push a fix soon :)

**Comment by ecosse3** [comment]
@AlanWarren Should be fixed now, please let me know :)

**Comment by AlanWarren** [comment]
@ecosse3 I had a chance to try it out, and everything appears functional.  Appreciate it!
