### ISSUE TITLE
How to uninstall this plugin it messed my whole nvim?

### ISSUE THREAD

**Issue by mahidharkakumani** [ecosse3/nvim#56]

**Comment by ecosse3** [comment]
Ecovim is not a plugin. It's a preconfigured Neovim instance. What problem do you have?

If you want to remove everything and start with fresh neovim remove `~/.config/nvim` directory as well as `~/.local/share/nvim`.

**Comment by ecosse3** [comment]
@mahidharkakumani Is your issue solved?
