### ISSUE TITLE
Everything is broken and it's related to winbar maybe?

### ISSUE THREAD

**Issue by XenoWad01** [ecosse3/nvim#58]
https://github.com/ecosse3/nvim/issues/57#issue-1261013742

**Comment by ecosse3** [comment]
Do you have latest version of nvim nightly and Ecovim (1.9.0)? Dashboard has been removed recently. Please make sure after pull to run :PackerSync. Winbar works only in neovim 0.8+ and in recents commit I made a check to run it only with nightly version.

**Comment by ecosse3** [comment]
@XenoWad01 Should work now, please let me know!

**Comment by ecosse3** [comment]
@XenoWad01 Is your issue solved?
