### ISSUE TITLE
Keybindings and shortcuts explained

### ISSUE THREAD

**Issue by d0t15t** [ecosse3/nvim#63]
Hi,
Thanks for this config!
Once i updated to the latest neovim, the installer worked perfectly. 
Now I'm trying to understand your key-bindings. For instance, could you please explain exactly what you mean for:

`<C - e>`

What keys is that exactly?

Is there a shortcut for toggling between opened files?
Or for searching for a file inside the File-Explorer?
Is it possible to open files next to each other in a split-display?
How do you comment out a single line?

Many thanks!

**Comment by d0t15t** [comment]
Thanks for the explanation! I'll try those...

**Comment by ecosse3** [comment]
@Jrcity If you have Prettier configured with ESLint you can use `<Leader>cf` mapping to format.

**Comment by Jrcity** [comment]
Can you help me out with your prettier config and how to go about with setting it up. Please.

**Comment by d0t15t** [comment]
Is it ok, if I keep these questions going?

- How do you achieve code-folding? To fold a long function, for instance...
- Is there a snippet/shortcut for `console.log(my_var)`?
- moving a whole block of text up or down N lines?

**Comment by Jrcity** [comment]
How do I read inline warnings and errors from a **.tsx** or **.ts** file
I was using the keybind **gl** but it does not seem to work

**Comment by ecosse3** [comment]
> How do I read inline warnings and errors from a .tsx or .ts file
I was using the keybind gl but it does not seem to work

@Jrcity `<leader>cl` is the keybinding for that. Feel free to remap for yourself.
