### ISSUE TITLE
Attempting to format any file returns error

### ISSUE THREAD

**Issue by techapostle** [ecosse3/nvim#65]
When calling on the format function or setting format on save for any given file, the following error is returned.  

Format:  
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'format' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk  

Format on save:  
Highlight group 'Normal' has no background highlight
Please provide an RGB hex value or highlight group with a background value for 'background_colour' option.
This is the colour that will be used for 100% transparency.
require("notify").setup({
  background_colour = "#000000",
})
Defaulting to #000000  

and attempting to save with this option:  
Error detected while processing BufWritePre Autocommands for "*":
Error executing lua callback: /home/kian/.config/nvim/lua/lsp/functions.lua:6: attempt to call field 'format' (a nil value)

**Comment by Akiletour** [comment]
Hi,

https://github.com/ecosse3/nvim/issues/45

Mae sure to have the latest neovim nightly version

**Comment by techapostle** [comment]
> Hi,
> 
> #45
> 
> Mae sure to have the latest neovim nightly version

Hello and thank you for your reply.  
I tested on neovim nightly and both format and format on save functions work as intended, however the warning about the Highlight group "Normal" having no background highlight still appears.  
However this should not be happening with the latest release of neovim (not nightly), as the Readme specifies compatibility with Neovim 0.7+, and does not state that the nightly build is required.  
If I could gain some more insight into why this is happening I can try to fix it myself.  

Thanks.
