### ISSUE TITLE
something wrong when loading the theme

### ISSUE THREAD

**Issue by scypurple** [ecosse3/nvim#67]
**environment:  mac os terminal.app + zsh latest**
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/14716045/175536739-6a252f56-10e7-4883-ab72-2479fa6dc095.png">

I haven't changed anything in `.config/neovim` 

>Something was wrong with the installation but I don't think that's a problem, still, I took a screenshot of the installation process.
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/14716045/175537880-205cf186-0851-4e07-a787-16386c1c60e9.png">

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/14716045/175537921-7fb2fea9-44f8-45e6-9152-779302f027fe.png">

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/14716045/175538101-4cf32df4-27a7-47e5-b011-cf86a03c2ee8.png">

**Comment by ecosse3** [comment]
If you want to use iTerm2 please take a look at configuring nerd font for that specific terminal. You have a link at end of the installation. Does this `which-key` error is visible during installation or after running ecovim later?

**Comment by scypurple** [comment]
I use mac own terminal with fira nerd font
<img width="703" alt="image" src="https://user-images.githubusercontent.com/14716045/175751801-e48cec56-07fb-41d2-bd8c-c1d801258c85.png">
`which-key` error is visiable during installation but now it has been installed

**Comment by scypurple** [comment]
Forgot to say, it's worked when I use iterm2.  Another question, how do I change its transparency?
