### ISSUE TITLE
zenmode error executing lua

### ISSUE THREAD

**Issue by MirceaDumitrescu** [ecosse3/nvim#69]
Fresh install, playing around in the dasboard and tried to enter zen mode

`E5108: Error executing lua ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:67: The coroutine failed with this message: ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:420: attempt to index upvalue 'signs' (a nil value)
stack traceback:
        ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua: in function 'reset_signs'
        ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/actions.lua:1127: in function <...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/actions.lua:1126>
stack traceback:
        [C]: in function 'error'
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:67: in function 'step'
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:83: in function 'execute'
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:114: in function 'refresh'
        ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/actions.lua:177: in function 'toggle_current_line_blame'
        /Users/mircea.dumitrescu/.config/nvim/lua/plugins/zen.lua:43: in function 'on_open'
        ...te/pack/packer/start/zen-mode.nvim/lua/zen-mode/view.lua:175: in function 'create'
        ...te/pack/packer/start/zen-mode.nvim/lua/zen-mode/view.lua:68: in function 'open'
        ...te/pack/packer/start/zen-mode.nvim/lua/zen-mode/view.lua:76: in function 'toggle'
        [string ":lua"]:1: in main chunk`

**Comment by ecosse3** [comment]
It has been fixed. Thanks for the issue!
