### ISSUE TITLE
Something wrong when format code with typescript

### ISSUE THREAD

**Issue by HungLe14** [ecosse3/nvim#71]
I had an issue which relates to format feature. Please help me!

![Screen Shot 2022-07-02 at 16 09 27](https://user-images.githubusercontent.com/99705956/176994263-94ceb2ff-9bf5-42cf-b280-433fa37c9f74.png)

**Comment by Akiletour** [comment]
Hi,

make sure to have the latest neovim version :)

**Comment by HungLe14** [comment]
Hi. I'm using the latest version
of nvim from brew. It is fine?

**Comment by ecosse3** [comment]
@HungLe14 Use the head version from homebrew:
`brew install neovim --HEAD`

**Comment by nevenduranec** [comment]
@ecosse3 I have installed the `brew install neovim --HEAD` but the error still exist.

Do we have to have the [`nightly`](https://github.com/neovim/neovim/releases/tag/nightly) release? And if yes, how to install the nightly version with brew?
