### ISSUE TITLE
Bad font icon show

### ISSUE THREAD

**Issue by alucard-ltd** [ecosse3/nvim#72]
<img width="49" alt="image" src="https://user-images.githubusercontent.com/52643141/177168102-c4f5cef6-f586-4ece-8afe-d6a7deb64803.png">
Iterm2

**Comment by ecosse3** [comment]
There was a mention after installation to configure fonts. You need to install patches nerd font (fira code recommended) from https://github.com/ryanoasis/nerd-fonts.

For iterm2 you need to configure terminal settings.

Not related to Ecovim.

**Comment by Developer27149** [comment]
@ecosse3 Hi there.I had config my ternimal font.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/23721611/198886542-f8b5055e-964c-44d6-9963-605fbd57c99f.png">
I am sure I had install firaCode and Hack font.
But. Icon show bad.
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/23721611/198886714-e6b10295-c6dd-4c0b-9ac2-7b2838d6da90.png">

I am a rookie.
Can you give me some sugestion? thanks. 😂

**Comment by Developer27149** [comment]
Got it.
- download font from [here](https://www.nerdfonts.com/font-downloads)
- uninstall old font and install new one
- set item2 text font

<img width="943" alt="image" src="https://user-images.githubusercontent.com/23721611/198891742-d43fd24d-de23-4f5f-98df-ea470d7ce25b.png">
