### ISSUE TITLE
Error when opening neovim for the first time after the installation of ecovim

### ISSUE THREAD

**Issue by MicheleFiladelfia** [ecosse3/nvim#73]
Errors executing /home/michele/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/michele/.config/nvim/lua/packer_commands.lua:1: attempt to call field '
nvim_create_user_command' (a nil value)
stack traceback:
        /home/michele/.config/nvim/lua/packer_commands.lua:1: in main chunk
        [C]: in function 'require'
        /home/michele/.config/nvim/init.lua:3: in main chunk
Error executing command line:
E492: Is not an editor command: PackerSync

**Comment by MicheleFiladelfia** [comment]
> What neovim version are you using?

0.6.1 cuz i have popos and if i run sudo apt install neovim it gives me this version.

If i install by flatpak it gives me 7.2 but your script says me that i dont have flatpak

**Comment by ecosse3** [comment]
That's because of that. Ecovim works with Neovim 0.7+ only. You need to update PPA or install from source.
