### ISSUE TITLE
tmux integration

### ISSUE THREAD

**Issue by al3rez** [ecosse3/nvim#74]
Hi Łukasz, by far this is the best and most well-thought dotfiles I've ever used, great job! Do you think it is it possible to integrate tmux into this? I'd love to have the status bar at least.

**Comment by ecosse3** [comment]
For now, I do not plan any tmux integration with Ecovim. I played with tmux for one day but I am using Kitty term daily and all its features of it (windows, kitty sessions, shortcuts) are satisfying to me. I don't see a reason to integrate status bar into tmux. Any PRs are welcome anyway.
