### ISSUE TITLE
Move from nvim-lsp-installer to Mason

### ISSUE THREAD

**Issue by alfredosdpiii** [ecosse3/nvim#80]
nvim-lsp-installer will no longer be maintained I think we need to move to mason. 

https://github.com/williamboman/nvim-lsp-installer/discussions/876

**Comment by ecosse3** [comment]
Thanks for the suggestion. I'll move Ecovim to Mason soon. It's crazy how often they're changing installer plugins, it's already 3 times.

**Comment by alfredosdpiii** [comment]
Yeah but this seems a better way of implementing installer plugins since it's all in one and includes DAP adapters, linters, etc. I think it'll last longer than the previous implementations since the extension for mason ( mason-lspconfig ) works with lspconfig. I have a fork of your config and switched it over to Mason and I think it works well.
