### ISSUE TITLE
Auto-indent broken for .tsx files

### ISSUE THREAD

**Issue by NiloDrumond** [ecosse3/nvim#84]
Auto-indent works fine on .ts files, but not on .tsx

.ts
![image](https://user-images.githubusercontent.com/48765760/183925179-434a2761-59a3-4a66-b59d-940ce2d5cb0e.png)

.tsx
![image](https://user-images.githubusercontent.com/48765760/183925253-bb8039de-48ed-44d6-81ab-7c7daa5bbde1.png)

**Comment by ecosse3** [comment]
I cannot reproduce this issue. Everything works as expected both in `ts` and `tsx`. I work with `tsx` daily. Did you install `tsx` and `typescript` treesitter parsers? `:TSInstall tsx`.

**Comment by NiloDrumond** [comment]
> I cannot reproduce this issue. Everything works as expected both in `ts` and `tsx`. I work with `tsx` daily. Did you install `tsx` and `typescript` treesitter parsers? `:TSInstall tsx`.
