### ISSUE TITLE
How can I remove node_modules from search  <S - pf> ?

### ISSUE THREAD

**Issue by hitfm00** [ecosse3/nvim#87]
<img width="1121" alt="Снимок экрана 2022-08-21 в 00 35 01" src="https://user-images.githubusercontent.com/21322208/185766714-087def05-5bcd-4903-82ef-55f16f0645b3.png">

**Comment by ecosse3** [comment]
By default, if you use any find files picker (via `<S-P>` or `<Leader-pf>`) it will fall back to `git files` if a git repo is found. If not it will fall back to find files that don't have any default ignored directories/files and it will search inside __node_modules__.

You can see in telescope wiki how to ignore specific dirs here: https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#file-and-text-search-in-hidden-files-and-directories

Ecovim function `project_files` also accepts optional `opts` so you can configure it here.

**Comment by hitfm00** [comment]
> By default, if you use any find files picker (via `<S-P>` or `<Leader-pf>`) it will fall back to `git files` if a git repo is found. If not it will fall back to find files that don't have any default ignored directories/files and it will search inside **node_modules**.
> 
> You can see in telescope wiki how to ignore specific dirs here: https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#file-and-text-search-in-hidden-files-and-directories
> 
> Ecovim function `project_files` also accepts optional `opts` so you can configure it here.
<img width="1427" alt="Снимок экрана 2022-08-21 в 22 49 55" src="https://user-images.githubusercontent.com/21322208/185808429-fa74fd04-c725-4dfd-9a26-61b7373894ac.png">

I have a problem with **git**, the `.git` folder is present, but for some reason after executing `<Leader-gs>` for example, it gives such an error, although it picks up my repository in a regular console and everything is fine displayed with the `git status` command

**Comment by ecosse3** [comment]
I see you're using my config on Windows machine which was not tested and it's not maintained by me. Maybe it can be somehow related to your local git client config and its support by Neovim/Telescope. In that case, I am not able to help you with that. You can open an issue on telescope repo or try to debug it by yourself.

**Comment by ecosse3** [comment]
Maybe it's somehow related to your local git configuration? Check if your root directory (via `:pwd`) is in git repository or sth like that. Maybe run `git init` in repo again. Not sure how I can help you with that information. It's a error from telescope repo.

**Comment by hitfm00** [comment]
`git config --global --add safe.directory /Users/maxim/Documents/NewLife/popcornLife
`
This command fixed my problem with  `is not a git directory` and after that search removed `node_modules`. Thx.
