### ISSUE TITLE
Error when fresh install

### ISSUE THREAD

**Issue by vbertaci** [ecosse3/nvim#88]
i'm getting a error when fresh install

`Error detected while processing /home/warlock/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/warlock/.config/nvim/lua/internal/pa
cker_commands.lua:1: attempt to call field 'nvim_create_user_command' (a nil val
ue)
stack traceback:
        /home/warlock/.config/nvim/lua/internal/packer_commands.lua:1: in main c
hunk
        [C]: in function 'require'
        /home/warlock/.config/nvim/init.lua:3: in main chunk
Error detected while processing command line:
E492: Not an editor command: PackerSync
`

OS: Ubuntu 22.04.1 LTS
nvim --version: 
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by ecosse3** [comment]
NVIM v0.6.1 is not supported as in README on top.
