### ISSUE TITLE
Can't format .scss files

### ISSUE THREAD

**Issue by hitfm00** [ecosse3/nvim#89]
When I trying to format a file `.scss` with <Leader-cf> he just throw error what 
`[LSP] Format request failed, no matching language servers.`

`:LspInfo`
<img width="1136" alt="Снимок экрана 2022-08-22 в 23 33 29" src="https://user-images.githubusercontent.com/21322208/186013596-6a7c30ba-09a3-46c1-9066-1a9df2ea34e4.png">
`

**Comment by ecosse3** [comment]
By default `default formatting provider` is disabled in css language server. It has to be enabled in `on_attach` method by:

```lua
  client.server_capabilities.documentFormattingProvider = true
  client.server_capabilities.documentRangeFormattingProvider = true
```

I'll add it soon to the config.

**Comment by hitfm00** [comment]
> By default `document formatting provider` is disabled in css language server. It has to be enabled in `on_attach` method by:
> 
> ```lua
>   client.server_capabilities.documentFormattingProvider = true
>   client.server_capabilities.documentRangeFormattingProvider = true
> ```
> 
> I'll add it soon to the config.
> 
> Edit: Implemented on `dev` branch. @hitfm00 You can check if it works 😊

I did this changes, now I have no this error `[LSP] Format request failed, no matching language servers.` but doesn't format :)

P.S. And one more question, how can I update **Ecovim**?)

**Comment by ecosse3** [comment]
It's just github repo. Pull the changes after switching to dev branch. I've tested it, it works on dev.

**Comment by hitfm00** [comment]
Yes, you are right, it's working, my bad :)
And I don't have a .git repository in nvim directory, I installed from this command:
`bash <(curl -s https://raw.githubusercontent.com/ecosse3/nvim/master/.install/run.sh)`

**Comment by ecosse3** [comment]
Great it works.

> And I don't have a `.git` repository in `nvim` directory,

That's actually weird. I was testing it in docker and git repository exists after a fresh install via script. Will check it later. You can always git init and add remote origin if needed.

**Comment by hitfm00** [comment]
@ecosse3 oh, sorry, I did this command and it's work now
`git config --global --add safe.directory /Users/maxim/.config/nvim`
