### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by pvamshi** [ecosse3/nvim#9]
Can you please write a 1-2 line guide on how to use this setup ? 🙏🏼

**Comment by ecosse3** [comment]
Hi, since I get this question quite often today I will work on installation shell script. I will let you know when it will be done!

**Comment by ecosse3** [comment]
@pvamshi I added the installation script. Please follow instructions from this PR: https://github.com/ecosse3/nvim/issues/10

I already started working on some guides on how I use my config and I will add more useful keybindings/actions I do while frontend programming. I'm going to publish it in couple of days.
