### ISSUE TITLE
Format on save - how to remove extra lines

### ISSUE THREAD

**Issue by hitfm00** [ecosse3/nvim#93]
When I format file, empty lines doesn't remove, maybe there is a setting for this?
And second question, maybe there is a setting for the quotes? For example I want to format all quote to single quote

<img width="411" alt="Снимок экрана 2022-08-31 в 20 18 08" src="https://user-images.githubusercontent.com/21322208/187740370-a21da80e-ee29-4201-8724-4bf8178dbf06.png">

**Comment by ecosse3** [comment]
This is not related to Ecovim but to your personal project configuration. Use specific ESLint rules together with Prettier to achieve this.
