### ISSUE TITLE
Window size resets when file opened from explorer

### ISSUE THREAD

**Issue by NiloDrumond** [ecosse3/nvim#94]
How to reproduce:
- `ctrl+w  v` to split window 50-50
- `leader` + `-` or `=` to change window sizes
- go to the file explorer/nvim-tree and open a file
- The result is that the window sizes will reset to 50-50

This does not happen when you open a file through Telescope or with `gd`

**Comment by ecosse3** [comment]
Fixed by switching `resize_window` flag in nvim-tree options. Will be released with next EcoVim version.
